### ISSUE TITLE
Face matches

### ISSUE THREAD

**Issue by stefi92** [betri28/FaceDetectCamera#1]
Hello, is it possbile to recognize face from camera and pair it with user in database? Next time when camera takes my photo, i want to compare if it matches with the saved one.

**Comment by betri28** [comment]
It's possbile, but you need a pro in face recognize to do that or you can use library OpenCV or Face API of microsoft.

**Comment by osmgunes** [comment]
hi I run this application on my device but app crashes the app crashes when ı press a button do you think this is about the permitions?
 here is the error
03-08 13:50:09.427 10286-10286/m.tri.facedetectcamera E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: m.tri.facedetectcamera, PID: 10286
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{m.tri.facedetectcamera/m.tri.facedetectcamera.activity.PhotoDetectActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.packageinstaller (has extras) }
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2585)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2667)
                                                                            at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                            at android.os.Looper.loop(Looper.java:207)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5776)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                                                                         Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.packageinstaller (has extras) }
                                                                            at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
                                                                            at android.app.Instrumentation.execStartActivity(Instrumentation.java:1641)
                                                                            at android.app.Activity.startActivityForResult(Activity.java:4647)
                                                                            at android.app.Activity.requestPermissions(Activity.java:3877)
                                                                            at android.support.v4.app.ActivityCompatApi23.requestPermissions(ActivityCompat23.java:32)
                                                                            at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:316)
                                                                            at m.tri.facedetectcamera.activity.PhotoDetectActivity.requestWriteExternalPermission(PhotoDetectActivity.java:221)
                                                                            at m.tri.facedetectcamera.activity.PhotoDetectActivity.onCreate(PhotoDetectActivity.java:74)
                                                                            at android.app.Activity.performCreate(Activity.java:6582)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2532)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2667) 
                                                                            at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                            at android.os.Looper.loop(Looper.java:207) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5776) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by betri28** [comment]
May be requestPermissions in some devices have bugs. You can fix by down  targetSdkVersion in grandle to below 23 (may be 22 or 21)

defaultConfig {
        applicationId "m.tri.facedetectcamera"
        minSdkVersion 11
        **targetSdkVersion 22**
        versionCode 1
        versionName "1.0"
}

**Comment by AnirudhSridhars** [comment]
I'm also having the same errors .Please help me
